# Generated by Django 6.0.1 on 2026-05-14 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True,
                        help_text="Причина отказа или заметка модератора",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "На модерации"),
                            (1, "Одобрена"),
                            (2, "Отклонена"),
                            (3, "Отменена"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "request_type",
                    models.IntegerField(
                        choices=[
                            (0, "Исключение времени занятия"),
                            (1, "Предпочтения по аудитории"),
                            (2, "Изменение в расписании"),
                            (3, "Бронирование аудитории"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="наименование")),
                (
                    "short_name",
                    models.CharField(max_length=5, verbose_name="сокращение"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="адрес")),
                (
                    "work_start_time",
                    models.TimeField(verbose_name="начало рабочего дня"),
                ),
                ("work_end_time", models.TimeField(verbose_name="конец рабочего дня")),
            ],
            options={
                "verbose_name": "корпус",
                "verbose_name_plural": "корпуса",
            },
        ),
        migrations.CreateModel(
            name="Constraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="имя метода")),
                (
                    "description",
                    models.TextField(max_length=255, verbose_name="описание"),
                ),
                (
                    "weight",
                    models.IntegerField(
                        help_text="Влияет на значение итоговой функции при генерации расписания",
                        verbose_name="вес",
                    ),
                ),
                (
                    "is_hard",
                    models.BooleanField(
                        default=False,
                        help_text="Запрещает публикацию варианта расписания если есть хоть одно занятие, с нарушением такого ограничения",
                        verbose_name="запретить нарушения",
                    ),
                ),
                (
                    "generation_only",
                    models.BooleanField(
                        default=False,
                        help_text="Информация о нарушении ограничения не будет выводится при ручном редактировании",
                        verbose_name="только для генератора",
                    ),
                ),
            ],
            options={
                "verbose_name": "ограничение",
                "verbose_name_plural": "ограничения",
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "allow_merge_teachers",
                    models.BooleanField(
                        default=False,
                        verbose_name="Разрешить объединение преподавателей",
                    ),
                ),
            ],
            options={
                "verbose_name": "дисциплина",
                "verbose_name_plural": "дисциплины",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="наименование")),
            ],
            options={
                "verbose_name": "оборудование",
                "verbose_name_plural": "оборудование",
            },
        ),
        migrations.CreateModel(
            name="LessonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Наименование")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Сокращение"
                    ),
                ),
                (
                    "allow_merge_teachers",
                    models.BooleanField(
                        default=False,
                        verbose_name="Разрешить объединение преподавателей",
                    ),
                ),
                (
                    "allow_merge_subgroups",
                    models.BooleanField(default=False, verbose_name="Вся группа"),
                ),
                (
                    "allow_merge_groups",
                    models.BooleanField(default=False, verbose_name="Весь поток"),
                ),
            ],
            options={
                "verbose_name": "вид занятия",
                "verbose_name_plural": "виды занятий",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="наименование"
                    ),
                ),
                (
                    "date_start",
                    models.DateField(unique=True, verbose_name="дата начала"),
                ),
                (
                    "date_end",
                    models.DateField(unique=True, verbose_name="дата окончания"),
                ),
            ],
            options={
                "verbose_name": "семестр",
                "verbose_name_plural": "семестры",
                "ordering": ["date_start"],
            },
        ),
        migrations.CreateModel(
            name="Timeslot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.PositiveSmallIntegerField(verbose_name="день")),
                (
                    "week_num",
                    models.PositiveSmallIntegerField(
                        verbose_name="номер недели в цикле"
                    ),
                ),
                (
                    "order_number",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="номер пары"
                    ),
                ),
                ("time_start", models.TimeField(verbose_name="время начала")),
                ("time_end", models.TimeField(verbose_name="время окончания")),
            ],
            options={
                "verbose_name": "слот расписания",
                "verbose_name_plural": "слоты расписания",
                "ordering": ["week_num", "day", "time_start"],
            },
        ),
        migrations.CreateModel(
            name="BuildingPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        help_text="Влияет на значение итоговой функции при генерации расписания",
                        verbose_name="приоритет",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.building",
                        verbose_name="клопус",
                    ),
                ),
            ],
            options={
                "verbose_name": "приоритет корпусов",
                "verbose_name_plural": "приоритеты корпусов",
                "ordering": ["institute", "building"],
            },
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.CharField(max_length=20, verbose_name="номер")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="наименование"
                    ),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="вместимость")),
                (
                    "eios_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID аудитории в системе EIOS",
                        null=True,
                        unique=True,
                        verbose_name="EIOS ID",
                    ),
                ),
                (
                    "allow_parallel",
                    models.BooleanField(
                        default=False, verbose_name="разрешить парралельные занятия"
                    ),
                ),
                (
                    "is_virtual",
                    models.BooleanField(
                        default=False, verbose_name="виртуальная аудитория"
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classrooms",
                        to="api.building",
                        verbose_name="корпус",
                    ),
                ),
                (
                    "equipment",
                    models.ManyToManyField(
                        blank=True,
                        related_name="classrooms",
                        to="api.equipment",
                        verbose_name="оснащение",
                    ),
                ),
            ],
            options={
                "verbose_name": "аудитория",
                "verbose_name_plural": "аудитории",
            },
        ),
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "short_name",
                    models.CharField(max_length=100, verbose_name="Сокращение"),
                ),
                (
                    "buildings_priority",
                    models.ManyToManyField(
                        related_name="institutes_priority",
                        through="api.BuildingPriority",
                        to="api.building",
                        verbose_name="Предпочитаемые корпуса для занятий",
                    ),
                ),
            ],
            options={
                "verbose_name": "институт",
                "verbose_name_plural": "институты",
                "ordering": ["short_name"],
            },
        ),
        migrations.AddField(
            model_name="buildingpriority",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.institute",
                verbose_name="институт",
            ),
        ),
        migrations.CreateModel(
            name="EquipmentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.discipline",
                        verbose_name="дисциплина",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.equipment",
                        verbose_name="оборудование",
                    ),
                ),
                (
                    "lesson_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.lessontype",
                        verbose_name="вид занятия",
                    ),
                ),
            ],
            options={
                "verbose_name": "требование к оснащению аудитории",
                "verbose_name_plural": "требования к оснащению аудиторий",
            },
        ),
        migrations.CreateModel(
            name="ScheduleScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="наименование")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="действующий"),
                ),
                (
                    "total_penalty",
                    models.IntegerField(
                        default=0, verbose_name="штраф по ограничениям"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.semester",
                        verbose_name="семестр",
                    ),
                ),
            ],
            options={
                "verbose_name": "вариант расписания",
                "verbose_name_plural": "варианты расписания",
                "ordering": ["semester", "is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admission_year",
                    models.PositiveIntegerField(verbose_name="Год поступления"),
                ),
                (
                    "learning_form",
                    models.CharField(max_length=20, verbose_name="Форма обучения"),
                ),
                (
                    "learning_stage",
                    models.CharField(max_length=100, verbose_name="Уровень подготовки"),
                ),
                (
                    "group_num",
                    models.CharField(max_length=5, verbose_name="Номер группы"),
                ),
                (
                    "sub_group_num",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер подгруппы"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Шифр")),
                (
                    "students_count",
                    models.PositiveIntegerField(verbose_name="Количество студентов"),
                ),
                (
                    "max_hours_per_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=35,
                        verbose_name="Максимальная нагрузка в неделю",
                    ),
                ),
                (
                    "max_hours_per_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=10,
                        verbose_name="Максимальная нагрузка в день",
                    ),
                ),
                ("sub_groups", models.ManyToManyField(blank=True, to="api.studygroup")),
            ],
            options={
                "verbose_name": "учебная группа",
                "verbose_name_plural": "учебные группы",
                "ordering": ["admission_year"],
            },
        ),
        migrations.CreateModel(
            name="AcademicLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merge_key", models.CharField(null=True, verbose_name="ключ связи")),
                (
                    "control_type",
                    models.CharField(
                        max_length=20, null=True, verbose_name="вид контроля"
                    ),
                ),
                (
                    "whole_hours",
                    models.PositiveIntegerField(verbose_name="всего часов"),
                ),
                (
                    "whole_weeks",
                    models.PositiveIntegerField(verbose_name="всего недель"),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.discipline",
                        verbose_name="дисциплина",
                    ),
                ),
                (
                    "lesson_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.lessontype",
                        verbose_name="вид занятия",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.semester",
                        verbose_name="семестр",
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loads",
                        to="api.studygroup",
                        verbose_name="группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "академическая нагрузка",
                "verbose_name_plural": "академические нагрузки",
            },
        ),
        migrations.CreateModel(
            name="StudyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=8, unique=True, verbose_name="Шифр"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Сокращение"
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_programs",
                        to="api.institute",
                        verbose_name="Институт",
                    ),
                ),
            ],
            options={
                "verbose_name": "направление подготовки",
                "verbose_name_plural": "направления подготовки",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="studygroup",
            name="study_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.studyprogram",
                verbose_name="Направление подготовки",
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "post",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "constraint_weight",
                    models.IntegerField(
                        default=1, verbose_name="Коэффицент приоритета ограничений"
                    ),
                ),
                (
                    "max_hours_per_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=35,
                        verbose_name="Максимальная нагрузка в неделю",
                    ),
                ),
                (
                    "max_hours_per_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=10,
                        verbose_name="Максимальная нагрузка в день",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.institute",
                        verbose_name="Институт",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "преподаватель",
                "verbose_name_plural": "преподаватели",
                "ordering": ["name", "institute"],
            },
        ),
        migrations.CreateModel(
            name="PlannedLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lessons_in_cycle",
                    models.PositiveIntegerField(
                        default=1, verbose_name="занятий за 2 недели"
                    ),
                ),
                (
                    "whole_weeks",
                    models.PositiveIntegerField(null=True, verbose_name="всего недель"),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Чем выше значение, тем раньше должно проводиться занятиеВлияет на значение итоговой функции при генерации расписания",
                        verbose_name="приоритет",
                    ),
                ),
                (
                    "academic_loads",
                    models.ManyToManyField(
                        to="api.academicload", verbose_name="источник"
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.discipline",
                        verbose_name="дисциплина",
                    ),
                ),
                (
                    "lesson_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.lessontype",
                        verbose_name="вид занятия",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.semester",
                        verbose_name="семестр",
                    ),
                ),
                (
                    "study_groups",
                    models.ManyToManyField(to="api.studygroup", verbose_name="группы"),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        to="api.teacher", verbose_name="преподаватели"
                    ),
                ),
            ],
            options={
                "verbose_name": "плановое занятие",
                "verbose_name_plural": "плановые занятия",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whole_weeks",
                    models.PositiveIntegerField(
                        null=True, verbose_name="количество недель"
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Чем выше значение, тем раньше должно проводиться занятиеВлияет на значение итоговой функции при генерации расписания",
                        verbose_name="приоритет",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.classroom",
                        verbose_name="аудитория",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.discipline",
                        verbose_name="дисциплина",
                    ),
                ),
                (
                    "lesson_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.lessontype",
                        verbose_name="вид занятия",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="api.schedulescenario",
                        verbose_name="сценарий",
                    ),
                ),
                (
                    "study_groups",
                    models.ManyToManyField(to="api.studygroup", verbose_name="группы"),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        to="api.teacher", verbose_name="преподаватели"
                    ),
                ),
                (
                    "timeslot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.timeslot",
                        verbose_name="слот расписания",
                    ),
                ),
            ],
            options={
                "verbose_name": "занятие",
                "verbose_name_plural": "занятия",
            },
        ),
        migrations.AddField(
            model_name="academicload",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loads",
                to="api.teacher",
                verbose_name="преподаватель",
            ),
        ),
        migrations.CreateModel(
            name="ScheduleAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.lesson"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.request"
                    ),
                ),
                (
                    "timeslot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.timeslot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "request_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.request",
                    ),
                ),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.classroom"
                    ),
                ),
            ],
            bases=("api.request",),
        ),
        migrations.CreateModel(
            name="ClassroomPreference",
            fields=[
                (
                    "request_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.request",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.classroom"
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.discipline"
                    ),
                ),
                (
                    "lesson_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.lessontype"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.teacher"
                    ),
                ),
            ],
            bases=("api.request",),
        ),
        migrations.CreateModel(
            name="ExcludedTimeslot",
            fields=[
                (
                    "request_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.request",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.teacher"
                    ),
                ),
                (
                    "timeslot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.timeslot"
                    ),
                ),
            ],
            bases=("api.request",),
        ),
        migrations.CreateModel(
            name="BuildingTravelTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "travel_time_minutes",
                    models.PositiveIntegerField(
                        verbose_name="Время перехода (в минутах)"
                    ),
                ),
                (
                    "from_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_from",
                        to="api.building",
                        verbose_name="стартовый корпус",
                    ),
                ),
                (
                    "to_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_to",
                        to="api.building",
                        verbose_name="конечный корпус",
                    ),
                ),
            ],
            options={
                "verbose_name": "время перехода между корпусами",
                "verbose_name_plural": "время перехода между корпусами",
                "unique_together": {("from_building", "to_building")},
            },
        ),
        migrations.AddConstraint(
            model_name="schedulescenario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("semester",),
                name="unique_active_record",
            ),
        ),
    ]
