# Generated by Django 6.0.1 on 2026-05-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plannedlesson",
            old_name="lessons_per_two_weeks",
            new_name="lessons_in_cycle",
        ),
        migrations.AddField(
            model_name="constraint",
            name="generation_only",
            field=models.BooleanField(
                default=False,
                help_text="Информация о нарушении ограничения не будет выводится при ручном редактировании",
                verbose_name="только для генератора",
            ),
        ),
        migrations.AddField(
            model_name="constraint",
            name="is_hard",
            field=models.BooleanField(
                default=False,
                help_text="Запрещает публикацию варианта расписания если есть хоть одно занятие, с нарушением такого ограничения",
                verbose_name="запретить нарушения",
            ),
        ),
        migrations.AlterField(
            model_name="buildingpriority",
            name="weight",
            field=models.IntegerField(
                help_text="Влияет на значение итоговой функции при генерации расписания",
                verbose_name="приоритет",
            ),
        ),
        migrations.AlterField(
            model_name="constraint",
            name="weight",
            field=models.IntegerField(
                help_text="Влияет на значение итоговой функции при генерации расписания",
                verbose_name="вес",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="priority",
            field=models.SmallIntegerField(
                blank=True,
                default=0,
                help_text="Чем выше значение, тем раньше должно проводиться занятиеВлияет на значение итоговой функции при генерации расписания",
                verbose_name="приоритет",
            ),
        ),
        migrations.AlterField(
            model_name="plannedlesson",
            name="priority",
            field=models.SmallIntegerField(
                blank=True,
                default=0,
                help_text="Чем выше значение, тем раньше должно проводиться занятиеВлияет на значение итоговой функции при генерации расписания",
                verbose_name="приоритет",
            ),
        ),
    ]
