# Generated by Django 6.0.1 on 2026-03-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='eios_id',
            field=models.IntegerField(blank=True, help_text='ID аудитории в системе EIOS', null=True, unique=True),
        ),
    ]
