# Generated by Django 6.0.1 on 2026-05-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="allow_lessons",
            new_name="allow_booking",
        ),
    ]
