# Generated by Django 6.0.1 on 2026-04-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Причина отказа или заметка модератора', null=True),
        ),
    ]
