# Generated by Django 6.0.1 on 2026-04-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicload",
            name="whole_weeks",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacher",
            name="post",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Должность"
            ),
        ),
    ]
