# Generated by Django 6.0.1 on 2026-05-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="constraint",
            name="generation_only",
        ),
        migrations.AddField(
            model_name="constraint",
            name="exclude_generation",
            field=models.BooleanField(
                default=False,
                help_text="При генерации расписания ограничение не будет учитываться",
                verbose_name="Исключить при генерации",
            ),
        ),
        migrations.AddField(
            model_name="constraint",
            name="exclude_manual",
            field=models.BooleanField(
                default=False,
                help_text="Информация о нарушении ограничения не будет выводиться при ручном редактировании расписания",
                verbose_name="Исключить при ручных изменениях",
            ),
        ),
    ]
