# Generated by Django 6.0.1 on 2026-05-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_constraint_generation_only_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="constraint",
            old_name="exclude_manual",
            new_name="generation_only",
        ),
        migrations.RenameField(
            model_name="constraint",
            old_name="exclude_generation",
            new_name="manual_only",
        ),
    ]
