# Generated by Django 6.0.1 on 2026-05-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_allow_lessons_classroom_allow_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="allow_lessons",
            field=models.BooleanField(
                default=True, verbose_name="разрешить проводить занятия в аудитории"
            ),
        ),
    ]
