# Generated by Django 6.0.1 on 2026-04-01 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_request_admin_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="academicload",
            old_name="hours_per_week",
            new_name="whole_hours",
        ),
        migrations.AlterField(
            model_name="academicload",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.semester",
            ),
        ),
    ]
