# Generated by Django 6.0.1 on 2026-05-01 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studygroup_learning_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='learning_form',
            field=models.CharField(max_length=20, verbose_name='Форма обучения'),
        ),
        migrations.CreateModel(
            name='PlannedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_count', models.PositiveIntegerField()),
                ('academic_loads', models.ManyToManyField(to='api.academicload')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discipline')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessontype')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semester')),
                ('study_groups', models.ManyToManyField(to='api.studygroup')),
                ('teachers', models.ManyToManyField(to='api.teacher')),
            ],
            options={
                'verbose_name': 'плановое занятие',
                'verbose_name_plural': 'плановые занятия',
            },
        ),
    ]
