# Generated by Django 6.0.1 on 2026-03-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classroom_eios_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='api.equipment'),
        ),
    ]
