# Generated by Django 6.0.1 on 2026-04-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_academicload_whole_weeks_alter_teacher_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ["institute"],
                "verbose_name": "преподаватель",
                "verbose_name_plural": "преподаватели",
            },
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="institeute",
            new_name="institute",
        ),
    ]
