# Generated by Django 6.0.1 on 2026-03-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_classroom_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicload",
            name="semester",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="building",
            name="short_name",
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="constraint",
            name="description",
            field=models.TextField(default="Описание", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="constraint",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
