# Generated by Django 6.0.1 on 2026-05-04 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_studygroup_learning_form_plannedlesson"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discipline",
            options={
                "ordering": ["name"],
                "verbose_name": "дисциплина",
                "verbose_name_plural": "дисциплины",
            },
        ),
        migrations.AlterModelOptions(
            name="institute",
            options={
                "ordering": ["short_name"],
                "verbose_name": "институт",
                "verbose_name_plural": "институты",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "занятие", "verbose_name_plural": "занятия"},
        ),
        migrations.AlterModelOptions(
            name="lessontype",
            options={
                "ordering": ["name"],
                "verbose_name": "вид занятия",
                "verbose_name_plural": "виды занятий",
            },
        ),
        migrations.AlterModelOptions(
            name="studyprogram",
            options={
                "ordering": ["code"],
                "verbose_name": "направление подготовки",
                "verbose_name_plural": "направления подготовки",
            },
        ),
        migrations.RemoveField(
            model_name="plannedlesson",
            name="lessons_count",
        ),
        migrations.AddField(
            model_name="lesson",
            name="whole_weeks",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="plannedlesson",
            name="hours_per_two_weeks",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="plannedlesson",
            name="whole_weeks",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="max_hours_per_week",
            field=models.PositiveSmallIntegerField(
                blank=True, default=35, verbose_name="Должность"
            ),
        ),
        migrations.AlterField(
            model_name="discipline",
            name="allow_merge_teachers",
            field=models.BooleanField(
                default=False, verbose_name="Разрешить объединение преподавателей"
            ),
        ),
        migrations.AlterField(
            model_name="discipline",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="institute",
            name="buildings_priority",
            field=models.ManyToManyField(
                related_name="institutes_priority",
                through="api.BuildingPriority",
                to="api.building",
                verbose_name="Предпочитаемые корпуса для занятий",
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="institute",
            name="short_name",
            field=models.CharField(max_length=100, verbose_name="Сокращение"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="api.schedulescenario",
                verbose_name="сценарий",
            ),
        ),
        migrations.AlterField(
            model_name="lessontype",
            name="allow_merge_groups",
            field=models.BooleanField(default=False, verbose_name="Весь поток"),
        ),
        migrations.AlterField(
            model_name="lessontype",
            name="allow_merge_subgroups",
            field=models.BooleanField(default=False, verbose_name="Вся группа"),
        ),
        migrations.AlterField(
            model_name="lessontype",
            name="allow_merge_teachers",
            field=models.BooleanField(
                default=False, verbose_name="Разрешить объединение преподавателей"
            ),
        ),
        migrations.AlterField(
            model_name="lessontype",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="lessontype",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Сокращение"
            ),
        ),
        migrations.AlterField(
            model_name="studyprogram",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_programs",
                to="api.institute",
                verbose_name="Институт",
            ),
        ),
    ]
