# Generated by Django 6.0.1 on 2026-04-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_hours_per_week_academicload_whole_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studygroup",
            name="sub_group_num",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
