# Generated by Django 6.0.1 on 2026-04-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyprogram",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Сокращение"
            ),
        ),
    ]
