# Generated by Django 6.0.1 on 2026-04-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_studyprogram_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyprogram",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Наименование"),
        ),
    ]
