# Generated by Django 6.0.1 on 2026-04-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='moodle_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID в Moodle'),
        ),
    ]
