upstream django_backend {
# Сервер backend
    server 127.0.0.1:8000;
}

server {
# Редирект на https
    listen 80;
    server_name diploma2026.uvelirsoft.ru;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name diploma2026.uvelirsoft.ru;

    # Сертификаты
    ssl_certificate /etc/ssl/usoft/ssl_2026/__uvelirsoft_ru.crt;
    ssl_certificate_key /etc/ssl/usoft/ssl_2026/private.key;

    # Проксирование API
    location /api/ {
        proxy_pass http://django_backend;
        include proxy_params;
    }

    # Проксирование Админки
    location /admin/ {
        proxy_pass http://django_backend;
        include proxy_params;
    }

    # Статика django
    location /static/ {
        alias /home/github/home/vkr-deploy/backend;
    }
    location /media/ {
        alias /home/github/home/vkr-deploy/media/;
    }

    # moodle
    location /moodle/ {
        proxy_pass http://localhost:8080;
        include proxy_params;
    }
    
    # Всё остальное
    location / {
        root /home/github/home/vkr-deploy/frontend/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}