from .base import *

DEBUG = False
STATIC_ROOT = "/app/static"
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
SRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')